version: '3'
services:
  web:
    depends_on:
      - "postgres"
    ports:
      - "8002:80"

  postgres:
    build: ./postgres
    ports:
      - "5432:5432"

  selenium-chrome:
    image: selenium/standalone-chrome

  testrunner:
    build: ./testrunner
    volumes:
      - ../../..:/var/www/html/portico
    environment:
      - WEBHOST=web
      - DBHOST=postgres
      - DBPORT=5432
      - DBNAME=porticotest
      - DBUSER=portico
      - DBPASSWORD=portico
      - DBDUMP=tests/_data/portico-test.sql
    depends_on:
      - "postgres"
      - "web"
      - "selenium-chrome"