
env:
  - DOCKER_COMPOSE_VERSION=1.18.0
sudo: required
services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose build

script:
  - docker-compose pull
  - docker-compose build
  - docker-compose up --abort-on-container-exit